package:
  name: dxchange
  version: '0.1.8'

source:
  git_url: https://github.com/data-exchange/dxchange.git
  
build:
  number: 0

requirements:
  build:
    - python
    - setuptools
 
  run:
    - python
    - numpy
    - scipy    
    - h5py    
    - netcdf4
    - spefile    
    - edffile    
    - tifffile    
    - dxfile
    - pandas
    
test:
  # Python imports
  imports:
    - dxchange
    - dxchange.reader
    - dxchange.writer
    - dxchange.exchange

about:
  home: http://dxchange.readthedocs.org
  license: BSD-3
  summary: 'Data I/O for tomography.'
